services:
  echo:
    build: ./server
    ports:
      - "34598:34598"

  stager:
    build: ./stager
    ports:
      - "34249:34249"
      - "34390:34390"

  minecraft:
    build: ./minecraft
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      VERSION: "26.1.2"
      ONLINE_MODE: "FALSE"
      JVM_OPTS: "-Dcom.sun.jndi.ldap.object.trustURLCodebase=true"
